name: Build Android App Bundle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Node.js & dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk 