name: Expo EAS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK (cloud)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Login to EAS
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Trigger EAS Build
        run: eas build --platform android --profile development --non-interactive
        env:
          EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }} 